name: build html
on: push

env: 
  KOSLI_ORG: Katerina-test
  KOSLI_FLOW: flow-test
  KOSLI_API_TOKEN: ${{ secrets.KOSLIAPI }}

jobs: 
    build: 
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v3
            with:
              fetch-depth: 100
          - name: Setup kosli cli
            uses: kosli-dev/setup-cli-action@v2
          - name: create kosli flow
            run: kosli create flow ${{ env.KOSLI_FLOW }} --template unit-test,snyk
            
          - name: report html
            run: kosli report artifact index.html --artifact-type file
            
