name: build html
on: push
jobs: 
    build: 
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v3
            with:
              fetch-depth: 100
          - name: Setup kosli cli
            uses: kosli-dev/setup-cli-action@v2
          - name: test
            run: kosli version
            
            
